2025-03-03 07:00:00 [ERROR]: Ошибка при получении заказов из Kaspi API: - Error: getaddrinfo ENOTFOUND kaspi-api-endpoint.kz
    at AxiosError.from (C:\Users\user\Desktop\bagaber-project\node_modules\axios\dist\node\axios.cjs:857:14)
    at RedirectableRequest.handleRequestError (C:\Users\user\Desktop\bagaber-project\node_modules\axios\dist\node\axios.cjs:3169:25)
    at RedirectableRequest.emit (node:events:536:35)
    at eventHandlers.<computed> (C:\Users\user\Desktop\bagaber-project\node_modules\follow-redirects\index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:512:5)
    at TLSSocket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at Axios.request (C:\Users\user\Desktop\bagaber-project\node_modules\axios\dist\node\axios.cjs:4258:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async KaspiService.fetchNewOrders (C:\Users\user\Desktop\bagaber-project\services\kaspiService.js:45:24)
    at async NotificationScheduler.checkNewOrders (C:\Users\user\Desktop\bagaber-project\services\notificationScheduler.js:43:22)
2025-03-03 07:00:00 [ERROR]: Ошибка при проверке новых заказов: - Error: Ошибка при получении заказов из Kaspi: getaddrinfo ENOTFOUND kaspi-api-endpoint.kz
    at KaspiService.fetchNewOrders (C:\Users\user\Desktop\bagaber-project\services\kaspiService.js:58:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async NotificationScheduler.checkNewOrders (C:\Users\user\Desktop\bagaber-project\services\notificationScheduler.js:43:22)
2025-03-03 07:04:35 [ERROR]: Ошибка подключения к базе данных RDS: - SequelizeHostNotFoundError: getaddrinfo ENOTFOUND your-rds-instance.region.rds.amazonaws.com
    at ConnectionManager.connect (C:\Users\user\Desktop\bagaber-project\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:96:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ConnectionManager._connect (C:\Users\user\Desktop\bagaber-project\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:222:24)
    at async C:\Users\user\Desktop\bagaber-project\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:174:32
    at async ConnectionManager.getConnection (C:\Users\user\Desktop\bagaber-project\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:197:7)
    at async C:\Users\user\Desktop\bagaber-project\node_modules\sequelize\lib\sequelize.js:305:26
    at async Sequelize.authenticate (C:\Users\user\Desktop\bagaber-project\node_modules\sequelize\lib\sequelize.js:457:5)
    at async testConnection (C:\Users\user\Desktop\bagaber-project\config\database.js:40:5)
    at async startServer (C:\Users\user\Desktop\bagaber-project\app.js:49:23)
2025-03-03 07:04:51 [ERROR]: Ошибка подключения к базе данных RDS: - SequelizeHostNotFoundError: getaddrinfo ENOTFOUND your-rds-instance.region.rds.amazonaws.com
    at ConnectionManager.connect (C:\Users\user\Desktop\bagaber-project\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:96:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ConnectionManager._connect (C:\Users\user\Desktop\bagaber-project\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:222:24)
    at async C:\Users\user\Desktop\bagaber-project\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:174:32
    at async ConnectionManager.getConnection (C:\Users\user\Desktop\bagaber-project\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:197:7)
    at async C:\Users\user\Desktop\bagaber-project\node_modules\sequelize\lib\sequelize.js:305:26
    at async Sequelize.authenticate (C:\Users\user\Desktop\bagaber-project\node_modules\sequelize\lib\sequelize.js:457:5)
    at async testConnection (C:\Users\user\Desktop\bagaber-project\config\database.js:40:5)
    at async startServer (C:\Users\user\Desktop\bagaber-project\app.js:49:23)
2025-03-03 07:05:06 [ERROR]: Ошибка подключения к базе данных RDS: - SequelizeHostNotFoundError: getaddrinfo ENOTFOUND your-rds-instance.region.rds.amazonaws.com
    at ConnectionManager.connect (C:\Users\user\Desktop\bagaber-project\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:96:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ConnectionManager._connect (C:\Users\user\Desktop\bagaber-project\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:222:24)
    at async C:\Users\user\Desktop\bagaber-project\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:174:32
    at async ConnectionManager.getConnection (C:\Users\user\Desktop\bagaber-project\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:197:7)
    at async C:\Users\user\Desktop\bagaber-project\node_modules\sequelize\lib\sequelize.js:305:26
    at async Sequelize.authenticate (C:\Users\user\Desktop\bagaber-project\node_modules\sequelize\lib\sequelize.js:457:5)
    at async testConnection (C:\Users\user\Desktop\bagaber-project\config\database.js:40:5)
    at async startServer (C:\Users\user\Desktop\bagaber-project\app.js:95:25)
2025-03-03 08:00:00 [ERROR]: Ошибка при получении заказов из Kaspi API: - AxiosError: Request failed with status code 404
    at settle (C:\Users\user\Desktop\bagaber-project\node_modules\axios\dist\node\axios.cjs:2031:12)
    at Unzip.handleStreamEnd (C:\Users\user\Desktop\bagaber-project\node_modules\axios\dist\node\axios.cjs:3148:11)
    at Unzip.emit (node:events:536:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
    at Axios.request (C:\Users\user\Desktop\bagaber-project\node_modules\axios\dist\node\axios.cjs:4258:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async KaspiService.fetchNewOrders (C:\Users\user\Desktop\bagaber-project\services\kaspiService.js:98:26)
    at async NotificationScheduler.checkNewOrders (C:\Users\user\Desktop\bagaber-project\services\notificationScheduler.js:43:22)
2025-03-03 08:00:00 [ERROR]: Ошибка при проверке новых заказов: - Error: Ошибка при получении заказов из Kaspi: Request failed with status code 404
    at KaspiService.fetchNewOrders (C:\Users\user\Desktop\bagaber-project\services\kaspiService.js:121:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async NotificationScheduler.checkNewOrders (C:\Users\user\Desktop\bagaber-project\services\notificationScheduler.js:43:22)
2025-03-03 08:17:16 [ERROR]: Ошибка при проверке статуса WhatsApp Cloud API: - [object Object]
2025-03-03 08:17:16 [ERROR]: Не удалось инициализировать WhatsApp Cloud API
